---
header-includes:
- \usepackage{lastpage}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO, CE]{Eddie Moon, 1004161916}
- \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
output:
  html_document:
    df_print: paged
  pdf_document: default
urlcolor: blue
---


```{r setup, message = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk.

# These are the packages you will need for this activity
packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = TRUE)
```


```{r getdata, eval = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk BUT...

# This chunk loads the most recent data from Toronto City and the data from OpenToronto.

# You have to RUN this chunk by hand to update the data as 
#   eval is set to FALSE to limit unnecessary requsts on the site.

###################################################
# Step one: Get the COVID data from Toronto City. #
###################################################

#googledrive::drive_deauth()

#url1 <- "https://drive.google.com/file/d/11KF1DuN5tntugNc10ogQDzFnW05ruzLH/view"
#googledrive::drive_download(url1, path="data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx", overwrite = TRUE)

#url2 <- "https://drive.google.com/file/d/1jzH64LvFQ-UsDibXO0MOtvjbL2CvnV3N/view"
#googledrive::drive_download(url2, path = "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx", overwrite = TRUE)

# this removes the url object that we don't need anymore
#rm(url1, url2)

#####################################################################
# Step two: Get the data neighbourhood data from Open Data Toronto. #
#####################################################################

nbhoods_shape_raw <- list_package_resources("neighbourhoods") %>% 
  get_resource()

saveRDS(nbhoods_shape_raw, "C:/Users/eddie/OneDrive/Desktop/skool/sta303/data/neighbourhood_shapefile.Rds")

nbhood_profile <- search_packages("Neighbourhood Profile") %>%
  list_package_resources() %>% 
  filter(name == "neighbourhood-profiles-2016-csv") %>% 
  get_resource()

saveRDS(nbhood_profile, "C:/Users/eddie/OneDrive/Desktop/skool/sta303/data/neighbourhood_profile.Rds")
```


```{r load_data, echo=FALSE}
######################################################
# Step three: Load the COVID data from Toronto City. #
######################################################

# Saving the name of the file as an object and then using the object name in the
# following code is a helpful practice. Why? If we change the name of the file 
# being used, we'll only have to change it in one place. This helps us avoid 
# 'human error'.

daily_data <- "C:/Users/eddie/OneDrive/Desktop/skool/sta303/a1data.xlsx"

# Cases reported by date
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type
outbreak_raw <- read_excel(daily_data, sheet = 3) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "C:/Users/eddie/OneDrive/Desktop/skool/sta303/a1data2.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################
# Step four: Load the neighbourhood data from Toronto City. #
#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("C:/Users/eddie/OneDrive/Desktop/skool/sta303/data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("C:/Users/eddie/OneDrive/Desktop/skool/sta303/data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format


```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Task 1: Daily cases
## Data wrangling

```{r cases_dw}
  
reported <- reported_raw %>%
  mutate_if(is.numeric, replace_na, replace=0) %>%
  rename(Recovered = recovered) %>%
  rename(Active = active) %>%
  rename(Deceased = deceased) %>%
  pivot_longer(-c(reported_date), names_to = "Type", values_to = "Count") %>%
  mutate(Type = fct_relevel(Type, "Recovered", after = 1))

reported$reported_date = date(reported$reported_date) 

```

\newpage
## Data visualization

```{r cases_vis}

reported %>%
  ggplot(aes(x=reported_date, y = Count, fill = Type)) +
  geom_bar(stat = "identity", width = 1) +
  scale_fill_manual(values = c("#003F5C", "#86BCB6", "#B9CA5D")) +
  scale_x_date(labels = scales::date_format("%d %b %y"), limits=c(date("2020-01-01"),Sys.Date())) +
  scale_y_continuous(limits = c(NA,2000)) +
  labs(title ="Cases reported by day in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: Eddie Moon for STA303/1002, U of T\nSource: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", date_daily[1,1])) +
  theme_minimal() +
  theme(legend.title = element_blank(), legend.position = c(.15, .8))

```

\newpage
# Task 2: Outbreak type
## Data wrangling


```{r outbreak_dw}

outbreak <- outbreak_raw %>%
  rename(Type = outbreak_or_sporadic) %>%
  rename(Week = episode_week) %>%
  rename(Cases = cases) %>%
  mutate(Type = fct_relevel(Type, "OB Associated", after = 1))

outbreak$Week = date(outbreak$Week) 

```

\newpage
## Data visualization

```{r outbreak_vis}

outbreak %>%
  ggplot(aes(x=Week, y = Cases, fill = Type)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#86BCB6", "#B9CA5D")) +
  scale_x_date(labels = scales::date_format("%d %b %y"), limits=c(date("2020-01-01"),Sys.Date()+7)) +
  scale_y_continuous(limits = c(NA,6800)) +
  labs(title ="Cases by outbreak type and week in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: Eddie Moon for STA303/1002, U of T\nSource: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", date_daily[1,1])) +
  theme_minimal() +
  theme(legend.title = element_blank(), legend.position = c(.15, .8))

```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1}

income <- nbhood_profile %>%
  filter(`_id` == 1143) %>%
  select(-c(Category, Topic, "Data Source", Characteristic)) %>%
  pivot_longer(-c(`_id`), names_to = "Neighbourhood", values_to = "Percentage")

income$Percentage = as.numeric(income$Percentage)

```

## Data wrangling: part 2

```{r nbhood_dw_2}

nbhoods_shape_raw[19, 7] = "North St. James Town"
nbhoods_shape_raw[41, 7] = "Weston-Pelham Park"
nbhoods_shape_raw[115, 7] = "Cabbagetown-South St. James Town"

nbhoods_all <- nbhoods_shape_raw %>%
  rename(neighbourhood_name = AREA_NAME) %>%
  mutate(neighbourhood_name = str_remove(neighbourhood_name, "\\s\\(\\d+\\)$")) %>%
  right_join(income,  by = c("neighbourhood_name" = "Neighbourhood")) %>%
  left_join(nbhood_raw,  by = c("neighbourhood_name" = "neighbourhood_name")) %>%
  rename(rate_per_100000 = rate_per_100_000_people) %>%
  filter(neighbourhood_name != "City of Toronto")

```

## Data wrangling: part 3

```{r nbhood_dw_3}

nbhoods_final <- nbhoods_all %>%
  mutate(med_inc = median(Percentage)) %>%
  mutate(med_rate = median(rate_per_100000)) %>%
  mutate(nbhood_type = case_when(
    (Percentage >= med_inc & rate_per_100000 >= med_rate) ~ "Higher low income rate, higher case rate",
    (Percentage >= med_inc & rate_per_100000 < med_rate) ~ "Higher low income rate, lower case rate",
    (Percentage < med_inc & rate_per_100000 >= med_rate) ~ "Lower low income rate, higher case rate",
    (Percentage < med_inc & rate_per_100000 < med_rate) ~ "Lower low income rate, lower case rate"))

```

\newpage
## Data visualization

```{r neighbourhood_graphs_1, fig.height=4}

nbhoods_final %>%
  ggplot() +
  geom_sf(aes(fill = Percentage)) +
  scale_fill_gradient(name = "% low income", low = "darkgreen", high = "lightgrey") +
  theme_map() +
  labs(title = "Percentage of 18 to 64 year olds living in a low income family (2015)",
       subtitle = "Neighbourhoods of Toronto, Canada",
       caption = str_c("Created by: Eddie Moon for STA303/1002, U of T\nSource: Census Profile 98-316-X2016001 via OpenData Toronto\n", date_nbhood[1,1])) +
  theme(legend.position = "right")

```

\newpage

```{r neighbourhood_graphs_2, fig.height=4}

nbhoods_final %>%
  ggplot() +
  geom_sf(aes(fill = rate_per_100000)) +
  scale_fill_gradient(name = "Cases per 100,000 people", low = "white", high = "darkorange") +
  theme_map() +
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: Eddie Moon for STA303/1002, U of T\nSource: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", date_nbhood[1,1])) +
  theme(legend.position = "right")

```

\newpage

```{r neighbourhood_graphs_3, fig.height=4}

nbhoods_final %>%
  ggplot() +
  geom_sf(aes(fill = nbhood_type)) +
  scale_fill_brewer(name = "% of 18 to 64 year-olds in\n low income families and\nCOVID-19 case rates", 
                    palette = "Set1") +
  theme_map() +
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: Eddie Moon for STA303/1002, U of T\nIncome data source: Census Profile 98-316-X2016001 via OpenData Toronto\nCOVID data source: Ontario Ministry of Health, Integrated Public \nHealth Information System and CORES\n", date_nbhood[1,1])) +
  theme(legend.position = "right")

```




```{r, eval = FALSE}
# This chunk of code helps you prepare your assessment for submission on Crowdmark
# This is optional. If it isn't working, you can do it manually/take another approach.

# Run this chunk by hand after knitting your final version of your pdf for submission.
# A new file called 'to_submit' will appear in your working directory with each page of your assignment as a separate pdf.

# Install the required packages
if(!match("staplr", installed.packages()[,1], nomatch = FALSE))
  {install.packages("staplr")}

# Don't edit anything in this function
prep_for_crowdmark <- function(pdf=NULL){
  # Get the name of the file you're currently in. 
  this_file <- rstudioapi::getSourceEditorContext()$path
  pdf_name <- sub(".Rmd", ".pdf", sub('.*/', '', this_file))
  
  # Create a file called to_submit to put the individual files in
  # This will be in the same folder as this file is saved
  if(!match("to_submit", list.files(), nomatch = FALSE))
    {dir.create("to_submit")}
 
  # Split the files
  if(is.null(pdf)){
  staplr::split_pdf(pdf_name, output_directory = "to_submit", prefix = "page_")} else {
    staplr::split_pdf(pdf, output_directory = "to_submit", prefix = "page_") 
  }
}

prep_for_crowdmark()

```